<?php ob_start();?>
<?php $_SESSION['something']='A value.'; ?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Justified Nav Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
   

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
    
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Toastr style -->
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/plugins/toastr/toastr.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/animate.css" rel="stylesheet">
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/style.css" rel="stylesheet">
    
    
  </head>

  <body>
      
          
          

    <div class="container animated fadeInDown">

     <div class="masthead">
        <h3 class="text-muted">Cf el desarrollo web en español hecho facíl</h3>
        <ul class="nav nav-justified">
          <li class="active"><a href="index">Inicio</a></li>
          <li><a href="proyectos">Proyectos</a></li>
          <li><a href="blog">Aprende</a></li>
          
          <li><a href="aporta">Aporta</a></li>
          <li><a href="acerca">Acerca de</a></li>
          <li><a href="contactos">Contactos</a></li>
          <li><a href="usuario/login">Login</a></li>
        </ul>
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Calima Framework</h1>
        <p class="lead">La forma eficaz, efectiva, segura y con la curva de aprendizaje mas rápida en la implementación de frameworks php en español.<br>Basado en la arquitectura MVC y con las mejores metodologías heredadas de los frameworks mas importantes.</p><p>Implemente aplicaciones web en minutos con nuestro motor MVC y la ayuda de Bootstrap 3.2.</p>
        <p><a class="btn btn-lg btn-success" href="https://github.com/webcol/Calima" role="button">Descárgalo hoy de github</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-3">
            <div class="widget-head-color-box navy-bg p-lg text-center">
          <h2>Rápido!</h2>
          
          <p class="text-justify">Descárgalo lee el install y ya estarás listo para usar una herramienta que te permitirá desarrollar aplicaciones y sitios web con una curva de aprendizaje muy corta. </p>
          <p><a class="btn btn-primary" href="#" role="button">Ver detalles &raquo;</a></p>
        </div>
            </div>
        <div class="col-lg-3">
            <div class="ibox-content text-center">
          <h2>Seguro!</h2>
          <p class="text-justify">Teniendo en cuenta la gran cantidad de mecanismos para el sabotaje, fuga de información y violación de tus sitios web, Cf cuenta con plugins que garantizan el buen funcionamiento del tu sistema web. </p>
          <p><a class="btn btn-primary" href="#" role="button">Ver detalles &raquo;</a></p>
       </div>
            </div>
        <div class="col-lg-3">
            <div class="widget-head-color-box navy-bg p-lg text-center">
          <h2>En tu Idioma</h2>
          <p class="text-justify">Una de las grandes problemáticas en la adopción de un frameworks es la gran cantidad de información que se debe aprender para su posterior implementación y desarrollo de algunas aplicaciones.</p>
          <p><a class="btn btn-primary" href="#" role="button">Ver detalles &raquo;</a></p>
        </div>
            </div>
          <div class="col-lg-3">
              <div class="ibox-content text-center">
          <h2>Responsive</h2>
          <p class="text-justify">Cf trae embebido el conocido framework bootstrap de twitter para que le des el toque artístico del diseño a tus trabajo, y lo mejor es la visualización en todos los dispositivos debido al responsive..</p>
          <p><a class="btn btn-primary" href="#" role="button">Ver detalles &raquo;</a></p>
        </div>
              </div>
      </div>

      <!-- Site footer -->
     

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>
