<!DOCTYPE html>
<html lang="en">
<head>	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="A Bootstrap Blog Template">
	<meta name="author" content="Vijaya Anand">

	<title>Home</title>

	<!-- Bootstrap CSS file -->
	<link href="<?PHP ECHO BASE_URL ?>/public_/css/bootstrap.min.css" rel="stylesheet" />
	<link href="<?PHP ECHO BASE_URL ?>/public_/css/bootstrap-theme.min.css" rel="stylesheet" />
	<link href="<?PHP ECHO BASE_URL ?>/public_/css/blog.css" rel="stylesheet" />
	
	
	
	
	
	

</head>




<body>
    
    
    <?php if(isset($this->postear) && count($this->postear)): ?>

          
	<!-- Header -->
	<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">			
		<div class="container">
			<div class="navbar-header">
				<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="index.html" class="navbar-brand">CfBlog</a>
			</div>
			<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
				
				<ul class="nav navbar-nav">
					<li class="active"><a href="index">Inicio</a></li>
					<li><a href="index">Servicios</a></li>
					<li><a href="apoyanos">Apoyanos</a></li>
					<li><a href="contactos">Contactos</a></li>
				</ul>
			</nav>
		</div>
	</header>

	<!-- Body -->
	<div class="container">
		<div class="row">
			<div class="col-md-8">

				<h1>Calima Blog</h1>
                                
                                
              
              <table>
              <tr>
               <?php for($i=0; $i<count($this->postear); $i++): ?>

				<article>
					<h2><a href="wikipost?id=<?php echo $this->postear[$i]['id']; ?>"><?php echo $this->postear[$i]['titulo']; ?></a></h2>

			        <div class="row">
			          	<div class="col-sm-6 col-md-6">
			          		<span class="glyphicon glyphicon-folder-open"></span> &nbsp;<a href="#">Autor: &nbsp;<?php echo $this->postear[$i]['autor']; ?> </a>
			          		&nbsp;&nbsp;<span class="glyphicon glyphicon-bookmark"></span> <a href="#">Aries</a>, <a href="#">Fire</a>, <a href="#">Mars</a>
			          	</div>
			          	<div class="col-sm-6 col-md-6">
			          		<span class="glyphicon glyphicon-pencil"></span> <a href="singlepost.html#comments">20 Comments</a>			          		
			          		&nbsp;&nbsp;<span class="glyphicon glyphicon-time"></span> <?php echo $this->postear[$i]['fecha']; ?>			          		
			          	</div>
			          </div>

			          <hr>

			          <img src="<?PHP ECHO BASE_URL ?>/public_/images/img/<?php echo $this->postear[$i]['imagen']; ?>" class="img-responsive">

			          <br />

			          <p class="lead"><?php echo $this->postear[$i]['descripcion']; ?>.</p>
                                  
                                  

			          <p><?php echo $this->postear[$i]['post']; ?>.</p>

					  <p class="text-right">
				          <a href="blog/wikipost?id=<?php echo $this->postear[$i]['id']; ?>">
				          	continue leyendo...
				          </a>
				      </p>

			          <hr>
				</article>

				<?php endfor; ?>
              
              </tr>
        
        
        </table>
					
				<ul class="pager">
					<li class="previous"><a href="#">&larr; Previous</a></li>
					<li class="next"><a href="#">Next &rarr;</a></li>
				</ul>

			</div>
			<div class="col-md-4">

				<div class="well text-center">
					<p class="lead">
						Si lo deseas puedes suscribirte para recibir nuestras Noticias continuas!
					</p>
					<button onclick="window.location.href='/contactos'" class="btn btn-primary btn-lg">Subscribete Hoy</button>
				</div>

				<!-- Latest Posts -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4>Últimos Post</h4>
					</div>
					<ul class="list-group">
						<li class="list-group-item"><a href="singlepost.html">1. Aries Sun Sign March 21 - April 19</a></li>
						<li class="list-group-item"><a href="singlepost.html">2. Taurus Sun Sign April 20 - May 20</a></li>
						<li class="list-group-item"><a href="singlepost.html">3. Gemini Sun Sign May 21 - June 21</a></li>
						<li class="list-group-item"><a href="singlepost.html">4. Cancer Sun Sign June 22 - July 22</a></li>
						<li class="list-group-item"><a href="singlepost.html">5. Leo Sun Sign July 23 - August 22 </a></li>
					</ul>
				</div>

				<!-- Categories -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4>Categorias</h4>
					</div>
					<ul class="list-group">
						<li class="list-group-item"><a href="#">Signs</a></li>
						<li class="list-group-item"><a href="#">Elements</a></li>
						<li class="list-group-item"><a href="#">Planets</a></li>
						<li class="list-group-item"><a href="#">Cusps</a></li>
						<li class="list-group-item"><a href="#">Compatibility</a></li>
					</ul>
				</div>

				<!-- Tags -->
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4>Tags</h4>
					</div>
					<div class="panel-body">
						<ul class="list-inline">
							<li><a href="#">Aries</a></li>
							<li><a href="#">Fire</a></li>
							<li><a href="#">Mars</a></li>
							<li><a href="#">Taurus</a></li>
							<li><a href="#">Earth</a></li>
							<li><a href="#">Moon</a></li>
							<li><a href="#">Gemini</a></li>
							<li><a href="#">Air</a></li>
							<li><a href="#">Mercury</a></li>
							<li><a href="#">Cancer</a></li>
						</ul>
					</div>
				</div>

				<!-- Recent Comments -->
				

			</div>
		</div>
	</div>

	<!-- Footer -->
	<footer>
		
	</footer>

	<!-- Jquery and Bootstrap Script files -->
	<script src="lib/jquery-2.0.3.min.js"></script>
	<script src="lib/bootstrap-3.0.3/js/bootstrap.min.js"></script>
        
        
              
              
          <?php else: ?>

          <p><strong>no hay post</strong></p>
          <?php endif; ?>
        
</body>
</html>
