<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="<?PHP ECHO Cf_BASE_URL ?>/public_/img/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/css/signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="<?PHP ECHO Cf_BASE_URL ?>/public_/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

        <form method="post" action="<?PHP ECHO Cf_BASE_URL ?>usuario/crearRegistro" class="form-horizontal">
        <h2 class="form-signin-heading">Registro</h2>
        <label for="inputEmail" class="sr-only">Nombre</label>
        <input name="nombre" type="text" class="form-control" id="name" placeholder="Nombre" required>
        <label for="inputEmail" class="sr-only">Apellido</label>
        <input name="apellido" type="text" class="form-control" id="apellido" placeholder="Apellido" required>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input name="email" type="text" class="form-control" id="email" placeholder="Email" required>
        <label for="inputPassword" class="sr-only">Password</label>
        <input name="clave"  type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button type="submit" class="btn btn-danger">Sign in</button>
	<button type="reset" class="btn btn-default">Reset</button>
        <div>
        <div class="widget-foot">
                 Already Registred? <a href="<?PHP ECHO Cf_BASE_URL ?>usuario">Login</a>
                </div>
        </div>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="<?PHP ECHO Cf_BASE_URL ?>/public_/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>