<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Cf | Register</title>

    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/animate.css" rel="stylesheet">
    <link href="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">Cf</h1>

            </div>
            <h3>Registro de usuarios</h3>
            <p>Registrate esperamos por ti.</p>
            <form method="post" action="<?PHP ECHO Cf_BASE_URL ?>usuario/crearRegistro" class="m-t" role="form" >
                <div class="form-group">
                    <input name="nombre" type="text" class="form-control" placeholder="Nombre" required="">
                </div>
                <div class="form-group">
                    <input name="email" type="email" class="form-control" placeholder="Email" required="">
                </div>
                <div class="form-group">
                    <input name="clave" type="password" class="form-control" placeholder="Password" required="">
                </div>
                <div class="form-group">
                        <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> Acepto los terminos y condiciones </label></div>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Registro</button>

                <p class="text-muted text-center"><small>Ya tienes una cuenta?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="<?PHP ECHO Cf_BASE_URL ?>usuario/login">Login</a>
            </form>
            
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/js/jquery-2.1.1.js"></script>
    <script src="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="<?PHP ECHO Cf_BASE_URL ?>/public_/inspinia/js/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
</body>

</html>