<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Error 404</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-blue">
    <div class="text-center">
        <a href="<?PHP ECHO Cf_BASE_URL ?>"><img src='<?PHP ECHO Cf_BASE_URL ?>public_/img/error404.png' alt='...'/></a>
    </div>
      <div class="text-center">
          <p>Houston tenemos un problema!  no encontrada tu petición</p>
          <a href="<?PHP ECHO Cf_BASE_URL ?>">Volver al Inicio</a>
    </div>

    
  </body>
</html>