  

  <body>

    <div class="container">

      <div class="masthead">
        <h3 class="text-muted"><?php  echo $this->titulo; ?></h3>
        <ul class="nav nav-justified">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Projects</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Downloads</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Framework MVC php</h1>
        <p class="lead">Un Framework liviano y de facil manejo con lo mejor de los Frameworks Php actuales.</p>
        <p><a class="btn btn-lg btn-success" href="https://github.com/webcol/Kalima/" role="button">Get started today</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
          <h2>Seguro!</h2>
          <p>Seguro con metodos que protegen el sistema contra ataques inyecion sql y xss.</p>
          
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Responsable</h2>
          <p>Creado para ser utilizado con bootstrap 3.0 para el servicio en diferentes dispositivos moviles. </p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>Rapido</h2>
          <p>Con un core el cual bajo su sencilles hace que las aplicaciones corrar en servidores con caracteristicas limitadas en hardware.</p>
          <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      

    </div> <!-- /container -->
