<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Justified Nav Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="<?PHP ECHO BASE_URL ?>public_/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../layout/default/css/justified-nav.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <div class="masthead">
        <h3 class="text-muted">PequeñoCMR</h3>
        <ul class="nav nav-justified">
          <li class="active"><a href="index">Inicio</a></li>
          <li><a href="#">Proyectos</a></li>
          <li><a href="aprende">Aprende</a></li>
          <li><a href="antes">Antes de iniciar</a></li>
		  <li><a href="aporta">Aporta</a></li>
          <li><a href="acerca">Acerca de</a></li>
          <li><a href="contactos">Contactos</a></li>
        </ul>
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Proyectos</h1>
        <p class="lead">PequeñoCMR aplicación de oficina para empresas con 50 empledos.</p><p>Desarrollado con CalimaFramework bajo la licencia Copyleft.</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Descargalo hoy</a></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
          <h2>Rapido!</h2>
          
          <p>Descargalo lee el install y ya estaras listo para usar una herramienta que te permitira desarrollar aplicaciones y sitios web con una curva de aprendisaje muy corta. </p>
          <p><a class="btn btn-primary" href="#" role="button">Ver detalles &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Seguro!</h2>
          <p>Teniendo en cuenta la gran cantidad de mecanismos para el sabotaje, fuga de informacion y violacion de tus sitios web, Cf cuenta con plugins que garantizan el buen funcionamiento del tu sistema web. </p>
          <p><a class="btn btn-primary" href="#" role="button">Ver detalles &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>En tu Idioma</h2>
          <p>Una de las grandes problematicas en la adopcion de un frameworks es la gran cantidad de informacion que se debe aprender para su posterior implementacion y desarrollo de algunas aplicaciones.</p>
          <p><a class="btn btn-primary" href="#" role="button">Ver detalles &raquo;</a></p>
        </div>
      </div>

      <!-- Site footer -->
     

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

